###Registro
POST http://127.0.0.1:8000/api/registro/
Content-Type: application/json

{
  "email": "test@gmail.com",
  "password": "123456",
  "rol": "tecnico"
}


###Login
POST http://127.0.0.1:8000/api/login/
Content-Type: application/json

{
  "email": "test@gmail.com",
  "password": "123456"
}


###Crear ticket
POST http://127.0.0.1:8000/api/tickets/
Authorization: Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6IjcwZmM5YzU0YjhiMjQyMWZmMTgyOTgxNTQyZmQ0NjRlOWJlYzM1NDUiLCJ0eXAiOiJKV1QifQ.eyJpc3MiOiJodHRwczovL3NlY3VyZXRva2VuLmdvb2dsZS5jb20vdHVybm9zLWE2ZDhkIiwiYXVkIjoidHVybm9zLWE2ZDhkIiwiYXV0aF90aW1lIjoxNzc2MTM2MDIyLCJ1c2VyX2lkIjoiak5Od0s2UTlGcFF0SWw4ZG9yQkVlUzBla1liMiIsInN1YiI6ImpOTndLNlE5RnBRdElsOGRvckJFZVMwZWtZYjIiLCJpYXQiOjE3NzYxMzYwMjIsImV4cCI6MTc3NjEzOTYyMiwiZW1haWwiOiJ0ZXN0QGdtYWlsLmNvbSIsImVtYWlsX3ZlcmlmaWVkIjpmYWxzZSwiZmlyZWJhc2UiOnsiaWRlbnRpdGllcyI6eyJlbWFpbCI6WyJ0ZXN0QGdtYWlsLmNvbSJdfSwic2lnbl9pbl9wcm92aWRlciI6InBhc3N3b3JkIn19.ugUBEhWexGriPRvAMwSs3w_ftSv0WeNwtWocdtckewcSNDU0Ti-VBQk9W33-TQYThBamauZ-G7WUhFfGAB8e6wKDezt7KrM2NkQOGVnAlc_RW9IrSRdndxuBLRl3wHtshvAfV3LZZq82BI0hZD3gHvXcAo2rQWu9RUyztyw5XsVGwQR932WgQrEY1gwZ7VqCFWxItEBaWdQZSjGC9O_d4yan-ohilb9VkZ4IlIc44r0u5Clgo_JrEvtAjB45JNRaPRCzQDfFmK4oomKPHGH0Cd9yNO3oXQyc5CzPCSJVGLkjMBW7Vv9o_e98VpPsb2nIJD3Uoi8eT8zErV8VkZOnqw
Content-Type: application/json

{
  "titulo": "El monitor encendio",
  "descripcion": "El monitor del laboratorio 6 enciende",
  "numero_equipo": "L6-05"
}


###Listar tickets
GET http://127.0.0.1:8000/api/tickets/
Authorization: Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6IjcwZmM5YzU0YjhiMjQyMWZmMTgyOTgxNTQyZmQ0NjRlOWJlYzM1NDUiLCJ0eXAiOiJKV1QifQ.eyJpc3MiOiJodHRwczovL3NlY3VyZXRva2VuLmdvb2dsZS5jb20vdHVybm9zLWE2ZDhkIiwiYXVkIjoidHVybm9zLWE2ZDhkIiwiYXV0aF90aW1lIjoxNzc2MTM3MTg1LCJ1c2VyX2lkIjoiak5Od0s2UTlGcFF0SWw4ZG9yQkVlUzBla1liMiIsInN1YiI6ImpOTndLNlE5RnBRdElsOGRvckJFZVMwZWtZYjIiLCJpYXQiOjE3NzYxMzcxODUsImV4cCI6MTc3NjE0MDc4NSwiZW1haWwiOiJ0ZXN0QGdtYWlsLmNvbSIsImVtYWlsX3ZlcmlmaWVkIjpmYWxzZSwiZmlyZWJhc2UiOnsiaWRlbnRpdGllcyI6eyJlbWFpbCI6WyJ0ZXN0QGdtYWlsLmNvbSJdfSwic2lnbl9pbl9wcm92aWRlciI6InBhc3N3b3JkIn19.SdD1DU3NwWWmXZSQmQrV4dCeBIW9gOj03E94Yk_7S8uE3-eM9cC8AKV9t_yeiVHrJiL2KwGZzvKTRmfDHqxZppi_5mWdxaOipviN2aH9e-6bAUVW2oWh7FENQ2w5cW8UJHIXfIvBtVbFp88I5IDdXyWITGbtZWQUX17WLi8cTq32LYEBlkJcYZRsqzHNTmu4GQpAUOep3ujBkZF-PsL4M_yl3TQVhChk-lyH_iTCgCBKgkRyXAQlACDc_5Ogbjwh0LI-etCRO4xVAukTN18iDExNXdBw1nQWdf1q-qCityH9UtKNQVOoIDdFlMKQAfhwzM0UnEOLH2totDSJk6soDA



###Filtrar tickets por estado
GET http://127.0.0.1:8000/api/tickets/?estado=pendiente
Authorization: Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6IjcwZmM5YzU0YjhiMjQyMWZmMTgyOTgxNTQyZmQ0NjRlOWJlYzM1NDUiLCJ0eXAiOiJKV1QifQ.eyJpc3MiOiJodHRwczovL3NlY3VyZXRva2VuLmdvb2dsZS5jb20vdHVybm9zLWE2ZDhkIiwiYXVkIjoidHVybm9zLWE2ZDhkIiwiYXV0aF90aW1lIjoxNzc2MTM3MTg1LCJ1c2VyX2lkIjoiak5Od0s2UTlGcFF0SWw4ZG9yQkVlUzBla1liMiIsInN1YiI6ImpOTndLNlE5RnBRdElsOGRvckJFZVMwZWtZYjIiLCJpYXQiOjE3NzYxMzcxODUsImV4cCI6MTc3NjE0MDc4NSwiZW1haWwiOiJ0ZXN0QGdtYWlsLmNvbSIsImVtYWlsX3ZlcmlmaWVkIjpmYWxzZSwiZmlyZWJhc2UiOnsiaWRlbnRpdGllcyI6eyJlbWFpbCI6WyJ0ZXN0QGdtYWlsLmNvbSJdfSwic2lnbl9pbl9wcm92aWRlciI6InBhc3N3b3JkIn19.SdD1DU3NwWWmXZSQmQrV4dCeBIW9gOj03E94Yk_7S8uE3-eM9cC8AKV9t_yeiVHrJiL2KwGZzvKTRmfDHqxZppi_5mWdxaOipviN2aH9e-6bAUVW2oWh7FENQ2w5cW8UJHIXfIvBtVbFp88I5IDdXyWITGbtZWQUX17WLi8cTq32LYEBlkJcYZRsqzHNTmu4GQpAUOep3ujBkZF-PsL4M_yl3TQVhChk-lyH_iTCgCBKgkRyXAQlACDc_5Ogbjwh0LI-etCRO4xVAukTN18iDExNXdBw1nQWdf1q-qCityH9UtKNQVOoIDdFlMKQAfhwzM0UnEOLH2totDSJk6soDA



###Actualizar estado de un ticket
PUT http://127.0.0.1:8000/api/tickets/2uClfydwG3pbLwrFmKSo/
Authorization: Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6IjcwZmM5YzU0YjhiMjQyMWZmMTgyOTgxNTQyZmQ0NjRlOWJlYzM1NDUiLCJ0eXAiOiJKV1QifQ.eyJpc3MiOiJodHRwczovL3NlY3VyZXRva2VuLmdvb2dsZS5jb20vdHVybm9zLWE2ZDhkIiwiYXVkIjoidHVybm9zLWE2ZDhkIiwiYXV0aF90aW1lIjoxNzc2MTM3MTg1LCJ1c2VyX2lkIjoiak5Od0s2UTlGcFF0SWw4ZG9yQkVlUzBla1liMiIsInN1YiI6ImpOTndLNlE5RnBRdElsOGRvckJFZVMwZWtZYjIiLCJpYXQiOjE3NzYxMzcxODUsImV4cCI6MTc3NjE0MDc4NSwiZW1haWwiOiJ0ZXN0QGdtYWlsLmNvbSIsImVtYWlsX3ZlcmlmaWVkIjpmYWxzZSwiZmlyZWJhc2UiOnsiaWRlbnRpdGllcyI6eyJlbWFpbCI6WyJ0ZXN0QGdtYWlsLmNvbSJdfSwic2lnbl9pbl9wcm92aWRlciI6InBhc3N3b3JkIn19.SdD1DU3NwWWmXZSQmQrV4dCeBIW9gOj03E94Yk_7S8uE3-eM9cC8AKV9t_yeiVHrJiL2KwGZzvKTRmfDHqxZppi_5mWdxaOipviN2aH9e-6bAUVW2oWh7FENQ2w5cW8UJHIXfIvBtVbFp88I5IDdXyWITGbtZWQUX17WLi8cTq32LYEBlkJcYZRsqzHNTmu4GQpAUOep3ujBkZF-PsL4M_yl3TQVhChk-lyH_iTCgCBKgkRyXAQlACDc_5Ogbjwh0LI-etCRO4xVAukTN18iDExNXdBw1nQWdf1q-qCityH9UtKNQVOoIDdFlMKQAfhwzM0UnEOLH2totDSJk6soDA
Content-Type: application/json

{
  "estado": "Resuelto"
}


###Obtener estadísticas de tickets
GET http://127.0.0.1:8000/api/tickets/estadisticas/
Authorization: Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6IjcwZmM5YzU0YjhiMjQyMWZmMTgyOTgxNTQyZmQ0NjRlOWJlYzM1NDUiLCJ0eXAiOiJKV1QifQ.eyJpc3MiOiJodHRwczovL3NlY3VyZXRva2VuLmdvb2dsZS5jb20vdHVybm9zLWE2ZDhkIiwiYXVkIjoidHVybm9zLWE2ZDhkIiwiYXV0aF90aW1lIjoxNzc2MTM3MTg1LCJ1c2VyX2lkIjoiak5Od0s2UTlGcFF0SWw4ZG9yQkVlUzBla1liMiIsInN1YiI6ImpOTndLNlE5RnBRdElsOGRvckJFZVMwZWtZYjIiLCJpYXQiOjE3NzYxMzcxODUsImV4cCI6MTc3NjE0MDc4NSwiZW1haWwiOiJ0ZXN0QGdtYWlsLmNvbSIsImVtYWlsX3ZlcmlmaWVkIjpmYWxzZSwiZmlyZWJhc2UiOnsiaWRlbnRpdGllcyI6eyJlbWFpbCI6WyJ0ZXN0QGdtYWlsLmNvbSJdfSwic2lnbl9pbl9wcm92aWRlciI6InBhc3N3b3JkIn19.SdD1DU3NwWWmXZSQmQrV4dCeBIW9gOj03E94Yk_7S8uE3-eM9cC8AKV9t_yeiVHrJiL2KwGZzvKTRmfDHqxZppi_5mWdxaOipviN2aH9e-6bAUVW2oWh7FENQ2w5cW8UJHIXfIvBtVbFp88I5IDdXyWITGbtZWQUX17WLi8cTq32LYEBlkJcYZRsqzHNTmu4GQpAUOep3ujBkZF-PsL4M_yl3TQVhChk-lyH_iTCgCBKgkRyXAQlACDc_5Ogbjwh0LI-etCRO4xVAukTN18iDExNXdBw1nQWdf1q-qCityH9UtKNQVOoIDdFlMKQAfhwzM0UnEOLH2totDSJk6soDA
